import '../models/speciality_model.dart';

abstract class SpecialtiesRepository {
  const SpecialtiesRepository();

  Future<List<Speciality>> getSpecialtiesList();

  Future<void> addSpeciality(
    String facultyBased,
    String name,
    String number,
    String about,
    String qualification,
    String trainingDurationDayFull,
    String trainingDurationDayShort,
    String trainingDurationCorrespondenceFull,
    String trainingDurationCorrespondenceShort,
    List<String> entranceTestsFull,
    List<String> entranceShort,
    String admissionCurrentDayFullBudget,
    String admissionCurrentDayShortBudget,
    String admissionCurrentDayFullPaid,
    String admissionCurrentDayShortPaid,
    String admissionCurrentCorrespondenceFullBudget,
    String admissionCurrentCorrespondenceShortBudget,
    String admissionCurrentCorrespondenceFullPaid,
    String admissionCurrentCorrespondenceShortPaid,
    String passScorePrevYearDayFullBudget,
    String passScorePrevYearDayShortBudget,
    String passScorePrevYearDayFullPaid,
    String passScorePrevYearDayShortPaid,
    String passScorePrevYearCorrespondenceFullBudget,
    String passScorePrevYearCorrespondenceShortBudget,
    String passScorePrevYearCorrespondenceFullPaid,
    String passScorePrevYearCorrespondenceShortPaid,
    String admissionPrevYearDayFullBudget,
    String admissionPrevYearDayShortBudget,
    String admissionPrevYearDayFullPaid,
    String admissionPrevYearDayShortPaid,
    String admissionPrevYearCorrespondenceFullBudget,
    String admissionPrevYearCorrespondenceShortBudget,
    String admissionPrevYearCorrespondenceFullPaid,
    String admissionPrevYearCorrespondenceShortPaid,
    String passScoreBeforeLastYearDayFullBudget,
    String passScoreBeforeLastYearDayShortBudget,
    String passScoreBeforeLastYearDayFullPaid,
    String passScoreBeforeLastYearDayShortPaid,
    String passScoreBeforeLastYearCorrespondenceFullBudget,
    String passScoreBeforeLastYearCorrespondenceShortBudget,
    String passScoreBeforeLastYearCorrespondenceFullPaid,
    String passScoreBeforeLastYearCorrespondenceShortPaid,
  );

  Future<void> editSpeciality(
    String facultyBased,
    String name,
    String number,
    String about,
    String qualification,
    String trainingDurationDayFull,
    String trainingDurationDayShort,
    String trainingDurationCorrespondenceFull,
    String trainingDurationCorrespondenceShort,
    List<String> entranceTestsFull,
    List<String> entranceShort,
    String admissionCurrentDayFullBudget,
    String admissionCurrentDayShortBudget,
    String admissionCurrentDayFullPaid,
    String admissionCurrentDayShortPaid,
    String admissionCurrentCorrespondenceFullBudget,
    String admissionCurrentCorrespondenceShortBudget,
    String admissionCurrentCorrespondenceFullPaid,
    String admissionCurrentCorrespondenceShortPaid,
    String passScorePrevYearDayFullBudget,
    String passScorePrevYearDayShortBudget,
    String passScorePrevYearDayFullPaid,
    String passScorePrevYearDayShortPaid,
    String passScorePrevYearCorrespondenceFullBudget,
    String passScorePrevYearCorrespondenceShortBudget,
    String passScorePrevYearCorrespondenceFullPaid,
    String passScorePrevYearCorrespondenceShortPaid,
    String admissionPrevYearDayFullBudget,
    String admissionPrevYearDayShortBudget,
    String admissionPrevYearDayFullPaid,
    String admissionPrevYearDayShortPaid,
    String admissionPrevYearCorrespondenceFullBudget,
    String admissionPrevYearCorrespondenceShortBudget,
    String admissionPrevYearCorrespondenceFullPaid,
    String admissionPrevYearCorrespondenceShortPaid,
    String passScoreBeforeLastYearDayFullBudget,
    String passScoreBeforeLastYearDayShortBudget,
    String passScoreBeforeLastYearDayFullPaid,
    String passScoreBeforeLastYearDayShortPaid,
    String passScoreBeforeLastYearCorrespondenceFullBudget,
    String passScoreBeforeLastYearCorrespondenceShortBudget,
    String passScoreBeforeLastYearCorrespondenceFullPaid,
    String passScoreBeforeLastYearCorrespondenceShortPaid,
    String id,
  );

  Future<void> removeSpeciality(String id);
}
